name: zxzc9992
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  connectivity_plus: ^1.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.1.2
  flutter_widget_from_html: ^0.8.1+1
  font_awesome_flutter: ^9.0.0
  google_mobile_ads: ^0.13.6
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  http: ^0.13.3
  image_picker: ^0.8.4+2
  loading_gifs: ^0.3.0
  nanoid: ^1.0.0
  path: ^1.7.0
  path_provider: ^2.0.1
  provider: ^5.0.0
  sqflite: ^2.0.0+3
  string_validator: ^0.3.0
  supabase: ^0.2.2
  theme_provider: ^0.5.0
  transparent_image: ^2.0.0
  uni_links: ^0.5.1
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
